# Phase 3B: Quick Cross-Dataset Validation - Circles
# Fast validation that capacity-adaptive scheduling works on medium complexity

experiment:
  name: "phase3b_quick_circles"
  description: "Quick capacity-adaptive validation on Circles medium complexity"
  phase: "phase3b"
  output_base: "phase3b"
  log_interval: 25
  seeds: [42]  # Single seed for quick test

device: "auto"

model:
  type: "SpectralMLP"
  hidden_dims: [32, 32]  # 32x32 predicted optimal for medium complexity

data:
  type: "Circles"
  n_samples: 1000
  noise: 0.1
  factor: 0.3
  random_state: 42

training:
  epochs: 50  # Shorter for quick validation
  learning_rate: 0.01
  optimizer: "adam"
  batch_size: null

regularization:
  type: "capacity_adaptive"
  beta: -0.2  # Validated optimal from Phase 3A
  sigma_base: 2.5
  final_sigma: 1.0
  strength: 0.1

metrics: ["accuracy", "loss", "criticality_score", "capacity_ratio"]