# Phase 2B: Exponential σ Schedule Dynamic Strategy
# Fast early decay from exploration to exploitation

experiment:
  name: "phase2b_exponential_schedule"
  description: "Exponential σ decay for rapid exploration-exploitation transition"
  log_interval: 10

model:
  type: "SpectralMLP"
  hidden_dims: [64, 64]

data:
  type: "TwoMoons"
  n_samples: 1000
  noise: 0.1
  random_state: 42

training:
  epochs: 100
  learning_rate: 0.01
  optimizer: "adam"
  batch_size: null

regularization:
  type: "exponential_schedule"
  initial_sigma: 2.5    # High σ for exploration
  final_sigma: 1.0      # Target σ for convergence  
  decay_rate: 5.0       # Controls decay speed
  strength: 0.1

experiment_config:
  seeds: [42, 123, 456, 789, 999]
  device: "cpu"