# Phase 2B: Static σ Comparison Baseline
# Fixed σ = 1.0 for direct comparison with dynamic strategies

experiment:
  name: "phase2b_static_comparison"
  description: "Fixed σ = 1.0 baseline for Phase 2B dynamic comparisons"
  log_interval: 10

model:
  type: "SpectralMLP"
  hidden_dims: [64, 64]

data:
  type: "TwoMoons"
  n_samples: 1000
  noise: 0.1
  random_state: 42

training:
  epochs: 100
  learning_rate: 0.01
  optimizer: "adam"
  batch_size: null

regularization:
  type: "fixed_spectral"
  target_sigma: 1.0     # Optimal σ from Phase 2A findings
  strength: 0.1

experiment_config:
  seeds: [42, 123, 456, 789, 999]
  device: "auto"