# Phase 2D-2A: 8x8 Single Seed Test
# Ultra-micro network: ~120 parameters total
# Test for actual runtime performance

experiment:
  name: "phase2d2_8x8_static_1seed"
  description: "Single seed test for 8x8 architecture timing"
  log_interval: 10
  seeds: [42]

device: "auto"

model:
  type: "SpectralMLP"
  hidden_dims: [8, 8]

data:
  type: "TwoMoons"
  n_samples: 1000
  noise: 0.1
  random_state: 42

training:
  epochs: 100
  learning_rate: 0.01
  optimizer: "adam"
  batch_size: null

regularization:
  type: "fixed_spectral"
  target_sigma: 1.0
  strength: 0.1

metrics: ["accuracy", "loss", "criticality_score"]